---
title: "Explaining Black-Box Models With LIME"
author: "Arash Amiririgi"
---

**Challenge:**
IBM has gathered information on employee satisfaction, income, seniority and some demographics. It includes the data of 1470 employees. In this regard, we are going to Visualize feature importance for a single and multiple explanation.

*Code:*

### Loading Libraries 
```{r message=FALSE, warning=FALSE}
library(h2o)
library(recipes)
library(readxl)
library(tidyverse)
library(tidyquant)
library(lime)
```

### Loading data
```{r message=FALSE, warning=FALSE}
employee_attrition_tbl <- read_csv("Employee_Attrition.csv")
definitions_raw_tbl <- read_excel("data_definitions.xlsx",
                                  sheet = 1, col_names = FALSE)
```

### Processing Pipeline
```{r message=FALSE, warning=FALSE}
source("00_Scripts/data_processing_pipeline.R")
employee_attrition_readable_tbl <- process_hr_data_readable(employee_attrition_tbl, definitions_raw_tbl)
```

### Assign training and test data
```{r message=FALSE, warning=FALSE}
set.seed(seed = 1113)
split_obj <- rsample::initial_split(employee_attrition_readable_tbl, prop = 0.85)
train_readable_tbl <- training(split_obj)
test_readable_tbl  <- testing(split_obj)
recipe_obj <- recipe(Attrition ~ ., data = train_readable_tbl) %>%
                step_zv(all_predictors()) %>%
                step_mutate_at(c("JobLevel", "StockOptionLevel"), fn = as.factor) %>% 
                prep()
train_tbl <- bake(recipe_obj, new_data = train_readable_tbl)
test_tbl  <- bake(recipe_obj, new_data = test_readable_tbl)
```


### Models
```{r message=FALSE, warning=FALSE}
h2o.init()

automl_leader <- h2o.loadModel("")
automl_leader
```



```{r message=FALSE, warning=FALSE}

```


```{r message=FALSE, warning=FALSE}

```





















