project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "01 Machine Learning Fundamentals"
            file: content/01_journal/01_Fundamentals.qmd
          - text: "02 Supervised ML - Regression"
            file: content/01_journal/02_Regression.qmd
          - text: "03 Automated Machine Learning with H2O (I)"
            file: content/01_journal/03_H2O_I.qmd
          - text: "04 Automated Machine Learning with H2O (II)"
            file: content/01_journal/04_H2O_II.qmd
          - text: "05 Performance Measures"
            file: content/01_journal/05_Performance_Measures.qmd
          - text: "06 Explaining Black-Box Models With LIME"
            file: content/01_journal/06_LIME.qmd
      - text: "Class notes"
        file: content/02_notes/05_class_notes.qmd
      - text: "Links"
        file: content/03_other/06_links.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto